export const HANDLER_ABI = [
  {
    type: "function",
    name: "doTransfer",
    inputs: [
      { name: "_token", type: "address", internalType: "address" },
      { name: "_from", type: "address", internalType: "address" },
      { name: "_to", type: "address", internalType: "address" },
      { name: "_value", type: "uint256", internalType: "uint256" },
      { name: "_deadline", type: "uint256", internalType: "uint256" },
      {
        name: "_priorityFee",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "_maxFeePerGas",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "_feeRate", type: "uint256", internalType: "uint256" },
      { name: "_gas", type: "uint256", internalType: "uint256" },
      { name: "_r", type: "bytes32", internalType: "bytes32" },
      { name: "_s", type: "bytes32", internalType: "bytes32" },
      { name: "_v", type: "uint8", internalType: "uint8" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getOpHash",
    inputs: [
      { name: "_token", type: "address", internalType: "address" },
      { name: "_from", type: "address", internalType: "address" },
      { name: "_to", type: "address", internalType: "address" },
      { name: "_value", type: "uint256", internalType: "uint256" },
      { name: "_deadline", type: "uint256", internalType: "uint256" },
      {
        name: "_priorityFee",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "_maxFeePerGas",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "_feeRate", type: "uint256", internalType: "uint256" },
      { name: "_gas", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "pure",
  },
  {
    type: "error",
    name: "Expired",
    inputs: [{ name: "_deadline", type: "uint256", internalType: "uint256" }],
  },
]
